### ISSUE TITLE
Anvil

### ISSUE THREAD

**Issue by Mangossa** [Hardel-DW/NeoEnchant#12]
When trying to use any item in a anvil,  get this error

The game crashed whilst container click
Error: kotlin.UninitializedPropertyAccessException: lateinit property dynamicRegistryManager has not been initialized

**Comment by Hardel-DW** [comment]
If it's on Realms, it's normal Mojang doesn't take experimental features like customs enchantments.

If you have more information, i can help you.
You can send level.dat file.
