### ISSUE TITLE
Deleting enchantments are more complex than the wiki states.

### ISSUE THREAD

**Issue by ekul6547** [Hardel-DW/NeoEnchant#13]
I guess just a bit of feedback, but the way it's described here:
https://github.com/Hardel-DW/NeoEnchant/wiki/Delete-an-enchantments#how-to-do-
Is very over-simplified and can break a lot of things.

In my case, I wanted to delete the vein miner & timber enchantments, as we already had server-side mods covering those.
But there are enchantment exclusive groups that reference these enchantment ids, so those had to be cleaned & fixed.
The advancement for the "spawner touch" has vein miner as a parent, so that had to be fixed.
And the loot tables will need to be cleaned if some enchantments are specifically named.
If these things are cleaned, then you get parsing errors for these jsons, which might make them non-functional.

It's not hard, I just think it's probably worth mentioning on the page that's it's not as simple as just removing the file.

**Comment by Hardel-DW** [comment]
Yes, all tagged files use "required: false" to avoid having to clean them. I hadn't thought about advancements, indeed.
I will update the documentation.
