### ISSUE TITLE
Certain blocks won't drop when mined when datapack is used on a Realm

### ISSUE THREAD

**Issue by loseruser656** [Hardel-DW/NeoEnchant#14]
Certain blocks like logs and stone won't drop when mined when the datapack is used on a realm. It works perfectly fine in the same world before the world is turned into a realm. Not sure what the problem is. This may have something to do with the datapack becoming a folder when uploaded to a realm. thanks

**Comment by Hardel-DW** [comment]
Mojang Realms doesn't load experimental feature like Enchantmets.
