### ISSUE TITLE
in advancement, json  need fix

### ISSUE THREAD

**Issue by qumingjam** [Hardel-DW/NeoEnchant#18]
https://pan.quark.cn/s/3f1828ab0fbd

for 1.21 
translate resourpack
advancement and enchant

仅用于1.21
汉化材质包
成就与附魔描述

**Comment by qumingjam** [comment]
[[1.21汉化]NeoEnchant.zip](https://github.com/user-attachments/files/16302613/1.21.NeoEnchant.zip)

**Comment by Hardel-DW** [comment]
I'll include it in a separate pack, thanks.
I'd like to include it directly in datapacks, I'm waiting for mojang to add the ability to combine resources pack and data packs.

**Comment by qumingjam** [comment]
In the process of my sinicization,I also found 2 duplicate references in the code。
They are the root.json and the list.json in the achievement

advancement.enchantplus.title.root
advancement.enchantplus.title.start

Both Tite and Description cite the same

Maybe it can be optimized in a later version

**Comment by Hardel-DW** [comment]
Thanks, I'll apply some modifications and add translations for the mod version.
