### ISSUE TITLE
Neoforge plans? 

### ISSUE THREAD

**Issue by ffuentesm** [Hardel-DW/NeoEnchant#21]
Just wondering if there are any plans to port this for Neoforge in 1.21
I've been using the datapack version, but is not the easiest to keep up to date, and modular with configs.

**Comment by Hardel-DW** [comment]
Currently, Modrinth automatically transforms the Datapack into a mod.
I don't think there's an option for NeoForge.
But I can do it by hand.

**Comment by Hardel-DW** [comment]
![image](https://github.com/user-attachments/assets/51c06956-5561-4b37-a295-845399733f5a)
Okay Modrinth added NeoForge
