### ISSUE TITLE
Spawner Touch Enchantment Issue: Unable to Recover Original Mob After Placing Spawner

### ISSUE THREAD

**Issue by Blk00000** [Hardel-DW/NeoEnchant#23]
Hello guys, I found a problem. After being able to apply the Spawner Touch enchantment to my pickaxe, the spawner breaks fine, but once placed, it’s impossible to recover the mob that was originally in the spawner (in this example, the spider). Thanks :)

![2024-09-28_22 05 51](https://github.com/user-attachments/assets/0f1fc5b0-8fc4-42c2-8014-312cb0836250)
![2024-09-28_22 05 38](https://github.com/user-attachments/assets/05235066-773f-4faf-beca-0956325d386c)
![2024-09-28_22 05 48](https://github.com/user-attachments/assets/9a031cbc-0a02-4b58-ba2c-32261f0d8aad)

**Comment by Hardel-DW** [comment]
Yes, it's normal, it works as expected.
It is designed to be used in combination with Pull.

But I'm thinking of adding a “Variant” enchantment system.
For more customization
