### ISSUE TITLE
[Suggestion] Add Enchantment description support

### ISSUE THREAD

**Issue by ffuentesm** [Hardel-DW/NeoEnchant#24]
Could you add Enchantment Description support for the enchantments in this mod? 
Especially now that Encahtnment Description updated to the newer versions of Minecraft. 
it would help a lot, so I do not need to keep opening the mod made to check what each enchantment does. 
And market is fit with the other enchantment during gameplay. 
![image](https://github.com/user-attachments/assets/0bd05143-1766-4516-a231-6a1b8fbbe5de)
![image](https://github.com/user-attachments/assets/d965e54f-8b88-4fc0-94d0-308a2526c4bc)

**Comment by Hardel-DW** [comment]
This is not a vanilla feature.
But I can add it with Java code in the mod.

**Comment by Hardel-DW** [comment]
It's now in the update 5.7.0.
