### ISSUE TITLE
[1.21.1] [Neoforge] Neoforge version not being recognized 

### ISSUE THREAD

**Issue by ffuentesm** [Hardel-DW/NeoEnchant#26]
neoforge 21.1.63

Log: https://pastebin.com/PyHQLJEY
![image](https://github.com/user-attachments/assets/acb5e07a-5426-4ed0-b2c8-0c521ba24109)

Looking at the jar file, it seems to be a Fabric/Quilt mod
![image](https://github.com/user-attachments/assets/7551f4bf-43a2-40bf-8148-d2b4e9556ad6)

**Comment by Hardel-DW** [comment]
Sorry for the inconvenience. Modrinth during automatic mod transformation forgot to include NeoForge file.
It's done now.
