### ISSUE TITLE
enchant

### ISSUE THREAD

**Issue by Jert360** [Hardel-DW/NeoEnchant#29]
hello I'm trying to find the Spawner Touch enchantment but I don't understand what Found in Yggdrasil means 
![image](https://github.com/user-attachments/assets/5d776b59-52de-4886-8070-cf106f5e9f0b)

**Comment by Hardel-DW** [comment]
Yes, it's a bit vague. I'll modify the documentation to make it clearer.

To keep it simple. If you can't find it, there are three levels of rarity.
Vault Ominous gives the rarest enchantments, like Spawner Touch.

**Comment by Jert360** [comment]
Thanks for responding :)do you have to take a potion of bad omen to increase the loots in yggdrasil?

**Comment by Hardel-DW** [comment]
From Yggdrasil 2.0.0. The Bad Omen effect transforms Alfheim into “Ominous Alfheim”, a more complicated version with more interesting rewards.
