### ISSUE TITLE
Poison Aspect does not work on players

### ISSUE THREAD

**Issue by 137-Trimethylxanthin** [Hardel-DW/NeoEnchant#33]
I was using the mod on my server and noticed that my friend did not get wither & poison effects.
I have tested this now for about 10 times, if there is a luck factor involved or if this is intentional, maybe you could write that in the wiki.

**Comment by Hardel-DW** [comment]
It's Fixed. There was an error that enchantment applied to Poison and Wither was applied to all non-player entities.

Poison will work on players.
Wither on non-players.
