### ISSUE TITLE
Pull Enchantment not pulling from correct folder/Incorrect Action folder name

### ISSUE THREAD

**Issue by damiona123** [Hardel-DW/NeoEnchant#34]
When i was testing why the Pull enchant was not giving eggs like at all, I saw that it was trying to pull from a table from "function enchantplus:actions/egg" when in reality the folder its Supposed to be taking from is named Pull instead of Egg. Simple really. I had fixed the issue by renaming "Pull" to "Egg" but just thought I should bring it to your attention

**Comment by Hardel-DW** [comment]
Fixed :3 Sorry for late response. I don't see many issues on Github
