### ISSUE TITLE
[1.21.1][Neoforge] Update crash on launch or when joining a world

### ISSUE THREAD

**Issue by ffuentesm** [Hardel-DW/NeoEnchant#47]
Neoforege 21.1.90
Mods-NeoEnchant-5.8.0-for-1.21-1.21.1.jar

Log: [latest.log](https://github.com/user-attachments/files/18206959/latest.log)

The new enchantment edits are causing problems on config load. 
Here is the error each enchantment is having https://pastebin.com/HzG18Qw9

**Comment by Hardel-DW** [comment]
Thanks for the bug report, I'll look into it myself.
It seems that version 1.21.2+ has been installed, I may have made a mistake somewhere.

**Comment by Hardel-DW** [comment]
![image](https://github.com/user-attachments/assets/acb408bd-3b52-4b82-be76-2b95562e3dd2)
It's updated, the .jar of 1.21 and 1.21.4 was reversed. I'm so stupid
