### ISSUE TITLE
Spawner Touch doesn't work, if other enchantments coexist on the pickaxe.

### ISSUE THREAD

**Issue by LDDSurfer** [Hardel-DW/NeoEnchant#7]
Instead of giving me the spawner, it just gives me xp and nothing else

**Comment by LDDSurfer** [comment]
![2024-06-13_22 00 32](https://github.com/Hardel-DW/NeoEnchant/assets/155183665/6af29e82-7420-42f4-b9cf-5fad9804e05e)
![2024-06-13_22 00 17](https://github.com/Hardel-DW/NeoEnchant/assets/155183665/64cfa1b9-97b6-4058-b751-71528d560d83)

**Comment by Hardel-DW** [comment]
Thanks for taking the time to report the bug!
I've just updated the pack to fix.

Datapacks Version: [Modrinth](https://modrinth.com/datapack/neoenchant/version/5.2.1)
Fabric/Forge/Quilt Version: [Modrinth](https://modrinth.com/datapack/neoenchant/version/5.2.1+mod)
