### ISSUE TITLE
GeyserMC Compatibility

### ISSUE THREAD

**Issue by Fnab-West** [Hardel-DW/NeoEnchant#9]
On my testing server with GeyserMC, when a bedrock client tries to enchant using books, are not able to:
(screenshot)
![image](https://github.com/Hardel-DW/NeoEnchant/assets/82403442/9ab5424c-4894-420d-a175-79a0ac3c347f)

**Comment by Hardel-DW** [comment]
Custom enchantments are official mojangs features.
Named Data-Driven Enchantments.

This is a missing feature in Geyser., This is a bug that should be reported to GeyserMC.
